name: Cron

on:
  schedule:
    # 16:00と24:00 (JST) に処理を実行する。
    # UTC の 07:00 は JST だと 16:00
    - cron: '0 7,15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        run: |
          python main.py

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated database dump"
          git pull
          git push
